# Site settings
title: Poly.py - Tools for 3D.

google_analytics: G-S9QPBW7EYH

baseurl:
url: poly-py.github.io

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  projects:
    output: true
    permalink: /projects/:path/
    
exclude: [Gemfile, Gemfile.lock]

# Sign up for beta form!
comment-post: https://docs.google.com/forms/d/e/1FAIpQLScMGVqI6QDomXlDkqG_DM7TBxslXtS8JhJH9iNhADf2WjsSYw
# Email / tool
comment-post-fields: [ entry.1448189702, entry.1417504055]